---
- hosts: jenkins
  become: yes
  remote_user: azureuser
  become_user: root
  tasks:
  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  # - name: Import jenkins key from url
  #   ansible.builtin.rpm_key:
  #     state: present
  #     key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  # - name: yum update
  #   yum:
  #     name: '*'
  #     state: latest

  # - name: Install java
  #   yum:
  #     name: java-11-openjdk-devel
  #     state: present

  # - name: Install jenkins
  #   yum:
  #     name: jenkins
  #     state: latest